



spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:sql.7326it.club}:${MYSQL_PORT:53306}/admin?characterEncoding=utf8&useSSL=false
    username: root
    password: ${MYSQL_ROOT_PASSWORD:7326itcx}
    driver-class-name: com.mysql.jdbc.Driver


aei:
  auth:
    clientId: aeizzz
    clientSecret: aeizzzSecret
    scope: all

#swagger配置
swagger:
  enabled: true
  title: spring-boot-starter-swagger
  description: Starter for swagger 2.x
  version: 1.0.0
  base-package: top.aei.code.controller
  authorization:
    name: Authorization
    key-name: Authorization

##mybatis-plus mapper xml 文件地址
mybatis-plus:
  mapper-locations: classpath*:mapper/*/*Mapper.xml
  ##mybatis-plus type-aliases 文件地址
  type-aliases-package: top.aei.code.entity
  global-config:
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    logic-delete-value: 1
    logic-not-delete-value: 0
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换



logging:
  pattern:
    console: "%d - %msg%n"
  level:
    top.aei.code: debug